export const ProductsPageData = [
  {
    id: 1,
    imgSrc: "https://m.media-amazon.com/images/I/71HHmxdfyFL._UX500_.jpg",
    brand: "U.S. Polo Assn",
    price: {
      actualPrice: 3999,
      discountPrice: 2000,
      discount: 40,
    },
    rating: 3,
    category: "Pants",
  },
  {
    id: 2,
    imgSrc: "https://m.media-amazon.com/images/I/71HHmxdfyFL._UX500_.jpg",
    brand: "U.S. Polo Assn. Denim Co.",
    price: {
      actualPrice: 3199,
      discountPrice: 1759,
      discount: 45,
    },
    rating: 4,
    category: "Pants",
  },
  {
    id: 3,
    imgSrc: "https://m.media-amazon.com/images/I/71HHmxdfyFL._UX500_.jpg",
    brand: "H&M Women Pink Collared Top",
    price: {
      actualPrice: 1000,
      discountPrice: 800,
      discount: 10,
    },
    rating: 4,
    category: "Shirts",
  },
  {
    id: 4,
    imgSrc: "https://m.media-amazon.com/images/I/71HHmxdfyFL._UX500_.jpg",
    brand: "U.S. Polo Assn. Denim Co",
    price: {
      actualPrice: 3599,
      discountPrice: 2699,
      discount: 25,
    },
    rating: 2,
    category: "Pants",
  },
  {
    id: 5,
    imgSrc: "https://m.media-amazon.com/images/I/71HHmxdfyFL._UX500_.jpg",
    brand: "DressBerry Women Mauve Analogue Watch",
    price: {
      actualPrice: 3099,
      discountPrice: 1084,
      discount: 65,
    },
    rating: 5,
    category: "Watches",
  },
  {
    id: 6,
    imgSrc: "https://m.media-amazon.com/images/I/71HHmxdfyFL._UX500_.jpg",
    brand: "Men Brown Factory Serviced Analogue Watch",
    price: {
      actualPrice: 10995,
      discountPrice: 6597,
      discount: 40,
    },
    rating: 3,
    category: "Watches",
  },
  {
    id: 7,
    imgSrc: "https://m.media-amazon.com/images/I/71HHmxdfyFL._UX500_.jpg",
    brand: "Men Red Rev T Analogue Watch",
    price: {
      actualPrice: 3999,
      discountPrice: 2000,
      discount: 40,
    },
    rating: 4,
    category: "Watches",
  },
  {
    id: 8,
    imgSrc: "https://m.media-amazon.com/images/I/71HHmxdfyFL._UX500_.jpg",
    brand: "Men Teal Blue Polo Collar Cotton Pure Cotton",
    price: {
      actualPrice: 1299,
      discountPrice: 714,
      discount: 45,
    },
    rating: 3,
    category: "Shirts",
  },
  {
    id: 9,
    imgSrc: "https://m.media-amazon.com/images/I/71HHmxdfyFL._UX500_.jpg",
    brand: "Brown Casual Shirt",
    price: {
      actualPrice: 3999,
      discountPrice: 2000,
      discount: 40,
    },
    rating: 2,
    category: "Shirts",
  },
];
